export const FETCH_USER = "FETCH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const SEARCH_COCKTAILS = "SEARCH_COCKTAILS";
export const CLEAR_COCKTAILS_LIST = "CLEAR_COCKTAILS_LIST";
export const SEARCH_SINGLE_COCKTAIL = "SEARCH_SINGLE_COCKTAIL";
export const SEARCH_INGREDIENT = "SEARCH_INGREDIENT";
export const SEARCH_INGREDIENT_ERROR = "SEARCH_INGREDIENT_ERROR";
export const CLEAR_INGREDIENT = "CLEAR_INGREDIENT";
export const SINGLE_COCKTAIL_ERROR = "SINGLE_COCKTAIL_ERROR";
export const COCKTAILS_SEARCH_ERROR = "COCKTAILS_SEARCH_ERROR";
export const FETCH_COCKTAILS_LIST = "FETCH_COCKTAILS_LIST";
export const POPULATE_AUTOCOMPLETE = "POPULATE_AUTOCOMPLETE";
export const AUTOCOMPLETE_EMPTY = "AUTOCOMPLETE_EMPTY";
export const FETCH_FAVE_COCKTAILS = "FETCH_FAVE_COCKTAILS";
export const FETCH_FAVE_COCKTAILS_ERROR = "FETCH_FAVE_COCKTAILS_ERROR";

export const CREATE_NEW_POST = "CREATE_NEW_POST"

